# User config
author: "Pakaki ğŸŒ¶ï¸"
tagline: "Pakaki - Tablas de balance"
description: "Juego libre | Entrenamiento funcional | Madera ğŸŒ³ | Pakaki = ğŸŒ¶ï¸ (segÃºn Mati)"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "pakaki@example.com"
# linkedin: "https://www.linkedin.com/"
# twitter: "https://twitter.com/"
# github: "https://github.com/"
instagram: "https://www.instagram.com/pakaki.balanceboard/"

# Site config
baseurl: "/pakaki"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
